kind: pipeline
name: test-and-quality
type: docker

trigger:
  event:
    - pull_request

steps:
  - name: setup_310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make setup.project
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD

  - name: py310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make test.unit
    depends_on:
      - setup_310

  - name: quality-checks
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make lints.ci
    depends_on:
      - setup_310

  - name: py39
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.9.16_poetry_1.4.0
    commands:
      - make setup.project
      - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    depends_on:
      - py310

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_SCANNER_FLAGS: -Dsonar.verbose=true
    depends_on:
      - py39
      - py310
      - quality-checks

---
name: publish-release-candidate
kind: pipeline
type: docker

trigger:
  branch:
    - main
  event:
    - push

steps:

  - name: setup_310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make setup.project
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD

  - name: py310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make test.unit
    depends_on:
      - setup_310

  - name: quality-checks
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make lints.ci
    depends_on:
      - setup_310

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_SCANNER_FLAGS: -Dsonar.verbose=true
    depends_on:
      - py310
      - quality-checks

  - name: publish-release-candidate
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    environment:
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    depends_on:
      - code-analysis
    commands:
      - make prep.pre.patch
      - make publish

  - name: publish-docs
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - git diff $DRONE_COMMIT_BEFORE..$DRONE_COMMIT_AFTER --name-only | grep docs/ && export DOC_CHANGE=1 || export DOC_CHANGE=0;
      - if [ $DOC_CHANGE ] ; then make publish.docs; else echo "No doc change"; fi
    depends_on:
      - code-analysis


---
name: publish-release
kind: pipeline
type: docker

trigger:
  branch:
    - main
  event:
    - tag

steps:
  - name: setup_310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make setup.project
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD

  - name: py310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make test.unit
    depends_on:
      - setup_310

  - name: quality-checks
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make lints.ci
    depends_on:
      - setup_310

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_SCANNER_FLAGS: -Dsonar.verbose=true
    depends_on:
      - py310
      - quality-checks

  - name: artifactory-poetry-publish
    when:
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    environment:
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    commands:
      # tag events validate poetry version is equal to the tag
      # increment patch version for releases based on drone tag
      - test "v$(poetry version --short)" "=" "$DRONE_TAG"
      - make publish
    depends_on:
      - code-analysis

