kind: pipeline
name: test-and-quality
type: docker

trigger:
  event:
    - pull_request
    - push
    - tag

steps:
  - name: setup
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make setup.project
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD

  - name: py39
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    depends_on:
      - setup

  - name: py310
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    depends_on:
      - py39 

  - name: quality-checks
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - make lints.ci
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    depends_on:
      - setup

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_RESOLVE_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
      SONAR_SCANNER_FLAGS: -Dsonar.verbose=true
    depends_on:
      - py39
      - py310
      - quality-checks

---
name: publish-release-candidate
kind: pipeline
type: docker

depends_on:
  - test-and-quality

trigger:
  event:
    - push
    - pull_request
  branch:
    - main

steps:
  - name: publish-release-candidate
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    environment:
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    commands:
      - make prep.pre.patch
      - make publish


---
name: publish-release
kind: pipeline
type: docker

depends_on:
  - test-and-quality

trigger:
  event:
    - tag
  branch:
    - main

steps:

  - name: artifactory-poetry-publish
    when:
      event:
        - tag
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    environment:
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_USERNAME:
        from_secret: ARTIFACTORY_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_DEPLOY_PASSWORD:
        from_secret: ARTIFACTORY_PYPI_PASSWORD
    commands:
      # tag events validate poetry version is equal to the tag
      # increment patch version for releases based on drone tag
      - test "v$(poetry version --short)" "=" "$DRONE_TAG"
      - make publish
      
---
kind: pipeline
type: docker
name: publish-docs

depends_on:
  - test-and-build

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: publish-docs
    image: harbor.shipttech.com/apps/python-images/shipt-python:3.10.10_poetry_1.4.0
    commands:
      - git diff $DRONE_COMMIT_BEFORE..$DRONE_COMMIT_AFTER --name-only | grep docs/ && export DOC_CHANGE=1 || export DOC_CHANGE=0;
      - if [ $DOC_CHANGE ] ; then make publish.docs; else echo "No doc change"; fi