[tool.poetry]
name = "opsml-artifacts"
version = "0.2.4"
description = "Package for creating, tracking, storing and versioning machine learning artifacts"
authors = ["Thorrester <48217609+thorrester@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<=3.11"
altair = "^4.2.0"
cloud-sql-python-connector = {version="^1.2.0", optional = true}
cryptography = "<39.0.0"
datamodel-code-generator = "^0.17.1"
fastapi = {version="^0.92.0", optional = true}
gcsfs = {version="^2022.11.0", optional = true}
google-auth = {version="1.35.0", optional = true}
google-cloud-scheduler = {version="^2.9.0", optional = true}
google-cloud-storage = {version="^2.2.1", optional = true}
graphviz = {version="^0.20.1", optional = true}
httpx = {version="^0.23.3", optional = true}
numpy = ">=1.21.6,<=1.24.1"
onnx = "^1.12.0"
onnxmltools = "^1.11.1"
onnxruntime = ">=1.13.0, <=1.13.1"
pandas = ">=1.4.0,<=1.5.3"
pg8000 = {version="^1.29.4", optional = true}
pyarrow = "8.0.0"
pydantic = ">=1.10.0, <=1.10.4"
pydantic-yaml = "^0.9.0"
pymysql = {version="^1.0.2", optional = true}
python-json-logger = "^2.0.6"
rollbar = {version="^0.16.3", optional = true}
scikit-learn = ">=1.0"
skl2onnx = "^1.13"
sqlalchemy = {extras = ["mypy"], version = "^1.4.46"}
tenacity = "^8.2.2"
tf2onnx = {version="^1.13.0", optional = true}
uvicorn = {version="^0.20.0", optional = true}
zarr = ">2.12.0"

[tool.poetry.extras]
api = ["fastapi", "uvicorn", "rollbar", "httpx"]
graphviz = ["graphviz"]
tf_onnx = ["tf2onnx"]
gcp_mysql = ["cloud-sql-python-connector","google-auth","google-cloud-storage",  "google-cloud-scheduler","gcsfs", "pymysql" ]
gcp_postgres = ["cloud-sql-python-connector","google-auth","google-cloud-storage",  "google-cloud-scheduler","gcsfs", "pg8000" ]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-lazy-fixture = "^0.6.3"
altair-viewer = "^0.4.0"
pytest-cov = "^3.0.0"
coverage = {extras = ["toml"], version = "^6.5.0"}
tensorflow = "2.10.1"
torch = "^1.13.1"
torchvision = "^0.14.1"
tabulate = "^0.9.0"
lightgbm = "^3.3.3"
xgboost = "^1.7.1"
mlflow = "^2.2.1"
llvmlite = "^0.39.1"
numba = "^0.56.0"

[tool.poetry.group.dev-lints]
optional = true

[tool.poetry.group.dev-lints.dependencies]
ruff = "^0.0.242"
sqlalchemy-stubs = "^0.4"
types-pymysql = "^1.0.19.1"
types-requests = "^2.28.11.7"
black = "22.3.0"
flake8 = "^4.0.1"
pylint = "^2.14.5"
isort = "^5.10.1"
sqlalchemy2-stubs = "0.0.2a32"
mypy = "1.0.0"
types-protobuf = "^4.21.0.3"
python-dotenv = "^0.21.1"


[tool.poetry.group.jupyter]
optional = true

[tool.poetry.group.jupyter.dependencies]
jupyterlab = "^3.6.1"

[tool.poetry.scripts]
load_model_card_to_file = "opsml_artifacts.scripts.load_model_card:load_model_card_to_file"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'

[tool.pylint.MASTER]
ignore-paths = [ "opsml_artifacts/.local_tests/*"]

[tool.pylint.messages_control]
max-line-length = 120
disable = [
    "too-few-public-methods",
    "design",
    "duplicate-code",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-many-nested-blocks",
    "unused-argument",
]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.flake8]
# This section is just a doc placeholder..see setup.cfg
max-complexity = 10
format = "pylint"
statistics = "True"
max-line-length = 120
# ignore non-PEP8 lints
ignore = ["E203", "W503"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = ["tests"]

[tool.mypy]
# platform configuration
python_version = "3.9"
platform = "linux"
mypy_path = "stubs"
ignore_missing_imports = true
plugins = [
    "numpy.typing.mypy_plugin",
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin",
    "sqlmypy",
]
exclude = ["opsml_artifacts/.local_tests/*", "opsml_artifacts/registry/sql/query_helpers.py"]


[tool.coverage.paths]
source = ["opsml_artifacts", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["opsml_artifacts"]

[tool.coverage.report]
show_missing = true
fail_under = 60


[tool.ruff]
line-length = 120

# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = []

# Exclude a variety of commonly ignored directories.
exclude = [
    "tests/",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.9.
target-version = "py39"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[build-system]
requires = ["poetry-core>=1.2.2"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
# Access Shipt's private Artifactory remote PyPi repository. It serves as a caching proxy.
# Generate Identity Token in Artifactory and use it as password and then have these ENV's set:
name = "shipt-resolve"
#url = "https://artifactory.gcp.shipttech.com/artifactory/api/pypi/pypi-local"
url = "https://artifactory.shipt.com/artifactory/api/pypi/pypi-virtual/simple"
default = true