version: '3.5'
services:
  webserver:
    container_name: opsml-docker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        PY_VER_FULL: 3.10.13
        OPSML_VERSION: 2.1.6
        OPSML_EXTRAS: "gcs, postgres, server"

    ports:
      - "8000:8000"

    command: >
      gunicorn 
      -k uvicorn.workers.UvicornWorker 
      --workers=4 
      --bind=0.0.0.0:8000 
      "opsml.app.main:run_app()"
