from enum import Enum


class OpsmlUri(str, Enum):
    STORAGE_URI = "OPSML_STORAGE_URI"
    TRACKING_URI = "OPSML_TRACKING_URI"
    RUN_ID = "OPSML_RUN_ID"


class OpsmlAuth(str, Enum):
    USERNAME = "OPSML_USERNAME"
    PASSWORD = "OPSML_PASSWORD"


class OpsmlPipelineVars(str, Enum):
    CONTAINER_REGISTRY = "OPSML_CONTAINER_REGISTRY"
    SCHEDULER_URI = "OPSML_SCHEDULER_URI"
    PIPELINE_HOST_URI = "OPSML_PIPELINE_HOST_URI"
    GCP_REGION = "OPSML_GCP_REGION"
