site_name: OpsML

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-night
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: stylesheets/extra.css
      accent: stylesheets/extra.css
      toggle:
        icon: material/weather-sunny
        name: light mode

  features:
    - navigation.sections
    - toc.follow
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/gear.png'

repo_name: opsml
repo_url: https://github.com/shipt/opsml
edit_uri: edit/main/docs/



nav:
  - Overview: 'index.md'
  - Installation: 'installation.md'
  - Quickstart: 'quickstart.md'
  - Cards:
      - 'cards/overview.md'
      - 'cards/versioning.md'
      - DataCard:
        - 'cards/datacard.md'
        - 'cards/data_profile.md'
        - 'cards/data_splits.md'
        - 'cards/image_dataset.md'
      - ModelCard:
        - 'cards/modelcard.md'
        - 'cards/challenger.md'
        - 'cards/model_metadata.md'
        - 'cards/onnx.md'
      - 'cards/runcard.md'
  - Server:
      - Setup: 'server/overview.md'
  - CLI:
      - Overview: 'cli/overview.md'
  - FAQ:
      - Common Questions: 'faq/common_questions.md'
  - Engineering:
      - Ownership: 'engineering/ownership.md'
  - RoadMap:
      - RoadMap: 'roadmap/roadmap.md'
 
markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings

extra_css:
- css/custom.css
- stylesheets/extra.css
- css/termynal.css
extra_javascript:
- js/termynal.js
- js/custom.js