[tool.poetry]
name = "opsml-server"
version = "0.1.0"
description = ""
authors = ["devops-ml"]

[tool.poetry.dependencies]
python = ">=3.9,<=3.11"
opsml = {version = "^0.41.0", extras = ["gcp-postgres", "server", "mlflow"]}
