name: Build Opsml Server Image

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      
jobs:
  build-gcs-310:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      env:
        OPSML_VERSION: "2.1.6"

      strategy:
        matrix:
          python_version: ["3.10.13", "3.11.7"]
          python_major_version: ["3.10", "3.11"]
          storage_backend: ["gcs"]
          sql_backend: ["postgres", "mysql"]
          exclude:
            - python_version: "3.10.13"
              python_major_version: "3.11"
            - python_version: "3.11.7"
              python_major_version: "3.10"

      steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - run : cp pyproject.toml poetry.lock  docker/ 

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: metadata
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: my-docker-hub-namespace/my-docker-hub-repository

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./docker/Dockerfile
            push: true
            tags: demml/opsml:${{matrix.python_version}}_${{matrix.storage_backend}}_${{matrix.sql_backend}}_v${{env.OPSML_VERSION}}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              PY_VER_FULL=${{matrix.python_version}}
              PY_VER_MAJOR=${{matrix.python_major_version}}
              OPSML_CMD=opsml[${{matrix.storage_backend}},${{matrix.sql_backend}},server]==${{env.OPSML_VERSION}}
         