name: Build Opsml Server Image

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      
jobs:
  build-gcs-310:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      env:
        PY_VER_FULL: "3.10.13"
        PY_VER_MAJOR: "3.10"
        OPSML_VERSION: "2.1.6"
      steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - run : cp pyproject.toml poetry.lock  docker/ 

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: my-docker-hub-namespace/my-docker-hub-repository

        - run: export OPSML_VERSION="v$(poetry version --short)"

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./docker/Dockerfile
            push: true
            tags: demml/opsml:${{env.PY_VER_FULL}}_gcs_pg_${{env.OPSML_VERSION}}
            labels: ${{ steps.meta.outputs.labels }}
            build-args: |
              PY_VER_FULL=${{env.PY_VER_FULL}}
              PY_VER_MAJOR=${{env.PY_VER_MAJOR}}
              OPSML_EXTRAS="gcs, server, postgres"
              OPSML_VERSION=$OPSML_VERSION