name: Lint-Unit-Test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      
jobs:
  Lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Install poetry
        run: echo "Test"
