name: Publish-PyPI

on:
  release:
    types: [published]

jobs:
  Unit-Lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.10",]
          poetry-version: ["1.5.1"]

      steps:
        - uses: actions/checkout@v3
        - name: Install poetry
          run: pipx install poetry==${{ matrix.poetry-version }}

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'poetry'
        - run : make setup.project
        - run : make lints.ci
        - run : make test.unit
        - run : make setup.project
        - run : test "v$(poetry version --short)" "=" "$GITHUB_REF_NAME"
        - run : poetry build

        - name: Publish
          uses: pypa/gh-action-pypi-publish@v1.8.6
          with:
            password: ${{ secrets.PYPI_TOKEN }}

