name: Publish-Github-Pages

on:
  workflow_run:
    workflows:
      - Publish-PyPI
    types:
      - completed

jobs:
  PublishDocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.5.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: make setup.project

      - name: Publish Docs
        run: make publish.docs
