name: Publish-Github-Pages

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize

jobs:
  PublishDocs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        poetry-version: ["1.5.1"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
            make setup.project
            
      - name: Publish Docs
        run: |
          git diff ${{github.event.before}}..${{github.sha}} --name-only | grep docs/ && export DOC_CHANGE=1 || export DOC_CHANGE=0;
          if [ $DOC_CHANGE ] ; then make publish.docs; else echo "No doc change"; fi
